[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"

[dev-dependencies]
rstest = "0.18"
criterion = "0.5"

[[bench]]
name = "all_days"
harness = false

[profile.bench]
debug = true